Crud\Domain\Model\User:
    type: entity
    table: users
    repositoryClass: Crud\Infrastructure\Repository\Doctrine\UserRepository
    indexes:
        role_id:
            columns:
                - role_id
    uniqueConstraints:
        email:
            columns:
                - email
    id:
        id:
            type: uuid
            nullable: false
            options:
                comment: 'User identifier'
            id: true
            generator:
                strategy: none
    fields:
#        roleId:
#            type: string
#            nullable: false
#            length: 40
#            options:
#                fixed: false
#                comment: 'Role identifier'
#            column: role_id
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 'E-mail address'
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 'User name'
        twitterHandle:
            type: string
            nullable: true
            length: 16
            options:
                fixed: false
                comment: 'Twitter username'
                default: 'NULL'
            column: twitter_handle
        password:
            type: string
            nullable: false
            length: 40
            options:
                fixed: false
                comment: 'Hashed password'
        created:
            type: datetime
            nullable: false
            options:
                comment: 'Add date'
        modified:
            type: datetime
            nullable: true
            options:
                comment: 'Modify date'
    manyToOne:
        role:
            targetEntity: Role
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                role_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
